### PR TITLE
enable checkstyle import check on apollo

### PR DESCRIPTION
**Pull request by Shoothzj**
## What's the purpose of this PR
enable checkstyle unused import check on apollo, guard #4825 

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/apolloconfig/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.

### CODE REVIEW

**Comment by nobodyiam** [comment]
Would you please provide more info on this pr? e.g. what kind of problems would be check by this plugin? 
BTW, can it check against the [apollo code style](https://github.com/apolloconfig/apollo/tree/master/apollo-buildtools/style)?

**Comment by Shoothzj** [comment]
@nobodyiam Now, I only enable the unused import check. Step by Step.
I think it can, we just need time to translate it to checkstyle rules.  :)

**Comment by nobodyiam** [comment]
review again

**Comment by nobodyiam** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Comment by nobodyiam** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

### Commit 1
The key changes in this patch are:

- The addition of a checkstyle.yml file with a GitHub Actions workflow that sets up a Maven Central Repository and runs the checkstyle check on the project.
- The addition of a checkstyle.xml file for configuring checkstyle, and a suppressions.xml file to prevent certain warnings from being reported.
- Removal of an unused import statement in the ReleaseBO.java file.
- Addition of the maven-checkstyle-plugin to the pom.xml file.

The potential problem in this patch is that the checkstyle configuration may not match the coding standards followed by the project. Therefore, it is important to thoroughly review the changes made in the configuration files to ensure that they align with the project's coding standards. Additionally, any new warnings that are generated by the checkstyle check should be carefully reviewed to ensure that they are accurate and meaningful.

**Pull request closed without merging**
