### PR TITLE
fix search user duplication issue

### LINKED ISSUE #4370: Search user duplication issue
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

When searching the users, if the keyword matches both the user name and user display name, there will be duplicated records displayed.

**To Reproduce**
1. Create users with user name and user display name the same
2. Search the user with the keyword

**Expected behavior**
There should be no duplicated records shown.

**Screenshots**
image

### Additional Details & Logs

- Version: 2.0.0

### PR DESCRIPTION
**Pull request by nobodyiam**
## What's the purpose of this PR

fix search user duplication issue

## Which issue(s) this PR fixes:
Fixes #4370

## Brief changelog

* use set to remove the duplicated records

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Comment by vdisk-group** [comment]
the `com.ctrip.framework.apollo.portal.entity.po.UserPO` does not override `equals()` and `hashcode()` method cause the `Set` dosen't work, using a `Map` might be better.

```java
...
    Map<Long, UserPO> users = new HashMap<>();
    List<UserPO> byUsername = userRepository
        .findByUsernameLikeAndEnabled("%" + keyword + "%", 1);
    List<UserPO> byUserDisplayName = userRepository
        .findByUserDisplayNameLikeAndEnabled("%" + keyword + "%", 1);
    if (!CollectionUtils.isEmpty(byUsername)) {
      for (UserPO user : byUsername) {
        users.put(user.getId(), user);
      }
    }
    if (!CollectionUtils.isEmpty(byUserDisplayName)) {
      for (UserPO user : byUserDisplayName) {
        users.put(user.getId(), user);
      }
    }
    return new ArrayList<>(users.values());
```

**Comment by nobodyiam** [comment]
@vdisk-group 

It seems the spring entity manager would make the entity object the same, so the HashSet still works.
image

But I agree what you propose is a better solution, so I have changed the implementation to what you suggested. Please help to review again.

**Comment by nobodyiam** [comment]
@vdisk-group 

It seems the spring entity manager would make the entity object the same, so the HashSet still works.
image

But I agree what you propose is a better solution, so I have changed the implementation to what you suggested. Please help to review again.

**Review by vdisk-group — APPROVED** [review]
LGTM

**Pull request merged**
