### PR TITLE
docs: add apollo rust client

### PR DESCRIPTION
**Pull request by liushv0**
## What's the purpose of this PR

add comment of rust adk for apollo

## Which issue(s) this PR fixes:
Fixes #None

## Brief changelog

docs: add  apollo rust client 

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by nisiyong** [comment]
Nice works! Thanks @liushv0 for contributing to the Rust language client.

And I think maybe we should use gRPC to replace the client protocol HTTP in the future to support multi-language, what do you think? @nobodyiam

**Comment by nobodyiam** [comment]
@nisiyong We may add the grpc support in the future but should still keep the HTTP/1.1 protocol for a while to make it backward compatible.

**Review by nobodyiam — APPROVED** [review]
LGTM

**Comment by nisiyong** [comment]
> @nisiyong We may add the grpc support in the future but should still keep the HTTP/1.1 protocol for a while to make it backward compatible.

It makes sense, we could do it in 2023.

**Pull request merged**
