### PR TITLE
Fixed flaky test

### PR DESCRIPTION
**Pull request by wang3820**
## What's the purpose of this PR

To fix flaky testing at `com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCacheTest#testAppNamespace`

## Which issue(s) this PR fixes:
`com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCacheTest#testAppNamespace` is flaky. 
Nondex was used to check and locate the flakiness in the test. The test can be reproduced using the following command:
```
mvn install -pl apollo-configservice -am -DskipTests
mvn -pl apollo-configservice test -Dtest=com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCacheTest#testAppNamespace
mvn -pl apollo-configservice edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCacheTest#testAppNamespace
```

## Brief changelog
Implementation of `appNamespaceIdCache` was changed from
https://github.com/wang3820/apollo/blob/5e49df687c64cf6f64f0210ba3ebc13084468757/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/service/AppNamespaceServiceWithCache.java#L87
to
https://github.com/wang3820/apollo/blob/66b66a972552733339d154504c785907d30c5249/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/service/AppNamespaceServiceWithCache.java#L72

`Maps.newConcurrentMap()` returns a `ConcurrentHashMap` object and its order is not maintained. When `keySet()` is called, this results in returning a null object. 

The nondex debug log:
```
TEST: com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCacheTest#testAppNamespace
java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
java.base/edu.illinois.nondex.common.NonDex.printStackTraceIfUniqueDebugPoint(NonDex.java:165)
java.base/edu.illinois.nondex.common.NonDex.shouldExplore(NonDex.java:136)
java.base/edu.illinois.nondex.common.NonDex.getPermutation(NonDex.java:106)
java.base/edu.illinois.nondex.shuffling.ControlNondeterminism.shuffle(ControlNondeterminism.java:93)
java.base/java.util.concurrent.ConcurrentHashMap$Traverser.<init>(ConcurrentHashMap.java:3342)
java.base/java.util.concurrent.ConcurrentHashMap$BaseIterator.<init>(ConcurrentHashMap.java:3424)
java.base/java.util.concurrent.ConcurrentHashMap$KeyIterator.<init>(ConcurrentHashMap.java:3445)
java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4625)
java.base/java.util.concurrent.ConcurrentHashMap$CollectionView.toArray(ConcurrentHashMap.java:4454)
java.base/java.util.ArrayList.<init>(ArrayList.java:179)
com.google.common.collect.Lists.newArrayList(Lists.java:146)
com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.updateAndDeleteCache(AppNamespaceServiceWithCache.java:181)
com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.lambda$afterPropertiesSet$0(AppNamespaceServiceWithCache.java:124)

```

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/apolloconfig/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/apolloconfig/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by wang3820** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wang3820** [comment]
recheck

**Comment by nobodyiam** [comment]
There was a similar pr #4998 merged, does the issue this pr try to solve still exist?

**Comment by wang3820** [comment]
> There was a similar pr #4998 merged, does the issue this pr try to solve still exist?

This PR appears to be reduntant as #4998 fixes the same issue. Closing this PR.

**Pull request closed without merging**
