### PR TITLE
feat(scripts): use bash to call openapi

### LINKED ISSUE #3941: openapi add bash scripts usage example
**Is your feature request related to a problem? Please describe.**
Some companies use openapi with bash scripts.

Provide examples of how to use openapi with bash scripts is worth doing, because those companies can use official bash scripts without write them by self.

We can provide some bash functions.

**Describe the solution you'd like**
1. Add those bash scripts to folder `scripts/openapi/bash`
2. Or Add those bash scripts to docs https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform

### PR DESCRIPTION
**Pull request by Anilople**
## What's the purpose of this PR

Provide basic functions to call openapi with bash scripts.

User can use it directly without write by self.

## Which issue(s) this PR fixes:

Fixes #3941

## Brief changelog

file:
* `.gitattributes`: add `*.sh text eol=lf`, let `.sh` file end with *nix style line `\n`.
* `scripts/openapi/bash/openapi.sh`: bash functions, user can use them.
* `scripts/openapi/bash/openapi-usage-example.sh`: a example to show how to use those bash functions.

run
```bash
cd scripts/openapi/bash
bash -x openapi-usage-example.sh
```
to view the result of bash scripts.

In bash scripts, use here document to make json string more readable.

Only cluster's get and create, if it is ok, more functions will be added in the feature.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by nobodyiam** [comment]
shall we also update the [open api usage document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform)?

**Comment by Anilople** [comment]
> shall we also update the [open api usage document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform)?

Of course.

**Comment by nobodyiam** [comment]
and also the CHANGES.md..

**Comment by nobodyiam** [comment]
please also update the [open api usage document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform)

**Comment by Anilople** [comment]
> please also update the [open api usage document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform)

Document has already been updated, is there more doc need to be add?

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
