### PR TITLE
Update ingress-portal.yaml

### PR DESCRIPTION
**Pull request by lijiansgit**
## What's the purpose of this PR

helm install error:
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set
ingress-portal.yaml syntax error:
-}} means whitespace to the right should be consumed，so apiVersion annotated

## Which issue(s) this PR fixes:
Fixes #

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by nobodyiam** [comment]
Thanks, would you please also help to fix ingress-configservice.yaml and ingress-adminservice.yaml?

**Comment by nobodyiam** [comment]
@lijiansgit is there any update on this?

**Comment by lijiansgit** [comment]
> 
> 
> @lijiansgit is there any update on this?

updated !

**Comment by lijiansgit** [comment]
> 
> 
> Thanks, would you please also help to fix ingress-configservice.yaml and ingress-adminservice.yaml?

updated !

**Comment by lijiansgit** [comment]
> 
> 
> @lijiansgit is there any update on this?

nothing !

**Comment by nobodyiam** [comment]
@lijiansgit please also sign the CLA and update the CHANGES.md, thanks!

**Comment by lijiansgit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
