### PR TITLE
Fix in text mode only the Item line number that is changed, not to update the Item last modified time.

### LINKED ISSUE #4482: 文本模式修改如果有key删除，会导致除被删除的key之外的所有key的最后修改时间变化
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

文本模式修改如果有key删除（非底部key），会导致除被删除的key之外的所有key的最后修改时间变化

**复现**

通过如下步骤可以复现：

文本模式随意删除一个key（非底部key），导致除被删除的key之外的所有key的最后修改时间变化

**期望**

文本模式删除key，应该只有被删除的key最后修改时间变化

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

### PR DESCRIPTION
**Pull request by mghio**
## What's the purpose of this PR

Fix in text mode only the Item line number that is changed, not to update the Item last modified time.

## Which issue(s) this PR fixes:
Fixes #4482

## Brief changelog

Remove Item lineNumber change check in PropertyResolver class.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.

### CODE REVIEW

**Comment by nobodyiam** [comment]
I think the line numbers would conflict in some situations, e.g.

```properties
Ln 1: a = 1
Ln 2: b = 2
Ln 3: c = 3
```

If we delete the first line and change the last line's value to 4

```properties
Ln 1: a = 1 <-- delete this line
Ln 2: b = 2
Ln 3: c = 4 <-- change c to 4
```

The result would be
```properties
Ln 2: b = 2
Ln 2: c = 4
```

**Comment by mghio** [comment]
Yes, it doesn't seem to work to remove the line number condition, because if the item is deleted in the middle, the following item line number will also be changed. Any suggestions?

**Comment by nobodyiam** [comment]
There is a built-in behavior to update the last modified time in BaseEntity, which makes it hard to tweak the behavior when only the line number is changed.
The difference between the table edit mode and text edit mode is that in the table edit mode, the user can only increment the line number by adding new items, however, in the text edit mode, the user can insert/delete some item in the middle which changes many items' line numbers.

https://github.com/apolloconfig/apollo/blob/4272471712141b46c323e87d385927409a8d276a/apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/BaseEntity.java#L131-L134

We may add some custom logic(e.g. a custom update statement that passes in the original last modified time) to keep the last modified time unchanged, however it depends on us to decide whether to support this feature or not..

```java
  @Modifying
  @Query("UPDATE Item SET LineNum = ?2, DataChange_LastTime = ?3 WHERE Id=?1 and IsDeleted = 0")
```

**Comment by mghio** [comment]
> There is a built-in behavior to update the last modified time in BaseEntity, which makes it hard to tweak the behavior when only the line number is changed. The difference between the table edit mode and text edit mode is that in the table edit mode, the user can only increment the line number by adding new items, however, in the text edit mode, the user can insert/delete some item in the middle which changes many items' line numbers.
> 
> https://github.com/apolloconfig/apollo/blob/4272471712141b46c323e87d385927409a8d276a/apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/BaseEntity.java#L131-L134
> 
> We may add some custom logic(e.g. a custom update statement that passes in the original last modified time) to keep the last modified time unchanged, however it depends on us to decide whether to support this feature or not..
> 
> ```java
>   @Modifying
>   @Query("UPDATE Item SET LineNum = ?2, DataChange_LastTime = ?3 WHERE Id=?1 and IsDeleted = 0")
> ```

Ok, thank you for your answer, I will close this PR and wait for the community to decide on a plan to deal with this problem.

**Pull request closed without merging**
