### PR TITLE
fix the potential data inconsistency issue

### LINKED ISSUE #3334: 覆盖了其他项目的配置项
今天突然发现有一个appid（假设为app-a）的某个配置项被变动了但是并没有发布，修改人为另外一个项目（假设名为app-b）的所有者（app-b-user），app-b-user对app-a并没有权限。看历史操作记录，此时间点app-b-user对app-b做了修改，但是在app-b的修改历史记录中看到的key却是app-a中被修改的那个key（这个key在app-b中并不存在）。

image

求查该问题根源的思路，目前看日志没有发现异常，在数据库中看到Commit表中的操作记录，该条操作记录的 ChangeSets字段中记录的原始namespaceId和key都是app-a的，但是AppId、ClusterName、NamespaceName 这几个字段都是app-b的。

目前觉得异常的地方是提交的这个键值是很大一长串的json格式的数据，里面包含有空格、tab和换行符之类的隐藏字符。是否这个原因导致了异常？

### PR DESCRIPTION
**Pull request by nobodyiam**
## What's the purpose of this PR

fix the potential data inconsistency issue when updating item by text

## Which issue(s) this PR fixes:
Fixes #3334

## Brief changelog

* add namespace id check before submitting the request to admin service

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by huayaoyue6** [comment]
此方式可以处理 https://github.com/apolloconfig/apollo/issues/3334 中提到的bug。但是我看adminservice中的
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java#L134
中添加了对namespaceId的判断，所以我不仅在portal模块中添加了和此pr一样的判断逻辑，也在adminservice中
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemSetController.java#L43
 判断了一下changeSet中是否存在多个namespaceId的情况。

**Comment by huayaoyue6** [comment]
此方式可以处理 https://github.com/apolloconfig/apollo/issues/3334 中提到的bug。但是我看adminservice中添加了对namespaceId的判断：
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java#L134
所以为了逻辑保持一致，所以我不仅在portal模块中添加了和此pr一样的判断逻辑，也在adminservice中判断了一下changeSet中是否存在多个namespaceId的情况：
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemSetController.java#L43

**Comment by huayaoyue6** [comment]
此方式可以处理 https://github.com/apolloconfig/apollo/issues/3334 中提到的bug。但是我看adminservice中添加了对namespaceId的判断：
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java#L134
所以为了保持逻辑的一致性，我不仅在portal模块中添加了和此pr一样的判断逻辑，也在adminservice中判断了一下changeSet中是否存在多个namespaceId的情况：
https://github.com/apolloconfig/apollo/blob/0ae4fc7629d64cb9a8a5c4b2e86bad763f21aca9/apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemSetController.java#L43

**Comment by nobodyiam** [comment]
@huayaoyue6 Thanks for the reminder and I think your solution is better. Would you please help to submit a pr to fix this issue?

**Comment by huayaoyue6** [comment]
我是双重判断。就几行代码，您要是方便直接在此pr上添加得了。

**Comment by huayaoyue6** [comment]
我是双重判断。就几行代码，您要是方便直接在此pr上追加得了。

**Comment by huayaoyue6** [comment]
我是双重判断。就几行代码，您要是方便直接在此pr上追加得了，关闭再提交又多折腾一下。

**Comment by nobodyiam** [comment]
@huayaoyue6 

> 所以为了保持逻辑的一致性，我不仅在portal模块中添加了和此pr一样的判断逻辑，也在adminservice中判断了一下changeSet中是否存在多个namespaceId的情况：

可以的，是否能贴一下这段的改动，我追加一下~

**Comment by huayaoyue6** [comment]
ItemSetController 

```java
package com.ctrip.framework.apollo.adminservice.controller;

import com.ctrip.framework.apollo.adminservice.aop.PreAcquireNamespaceLock;
import com.ctrip.framework.apollo.biz.service.ItemSetService;
import com.ctrip.framework.apollo.common.dto.ItemChangeSets;
import com.ctrip.framework.apollo.common.dto.ItemDTO;
import com.ctrip.framework.apollo.common.exception.BadRequestException;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ItemSetController {

  private final ItemSetService itemSetService;

  public ItemSetController(final ItemSetService itemSetService) {
    this.itemSetService = itemSetService;
  }

  @PreAcquireNamespaceLock
  @PostMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/itemset")
  public ResponseEntity<Void> create(@PathVariable String appId, @PathVariable String clusterName,
                                     @PathVariable String namespaceName, @RequestBody ItemChangeSets changeSet) {

    Set<Long> itemNamespaceIds = new HashSet<>(1);
    itemNamespaceIds.addAll(changeSet.getCreateItems().stream().map(ItemDTO::getNamespaceId).collect(Collectors.toSet()));
    itemNamespaceIds.addAll(changeSet.getUpdateItems().stream().map(ItemDTO::getNamespaceId).collect(Collectors.toSet()));
    itemNamespaceIds.addAll(changeSet.getDeleteItems().stream().map(ItemDTO::getNamespaceId).collect(Collectors.toSet()));

    if (itemNamespaceIds.size() > 1){
      throw new BadRequestException("Invalid request,multiple namespaceId found!");
    }

    itemSetService.updateSet(appId, clusterName, namespaceName, changeSet,"ItemSetController.create");

    return ResponseEntity.status(HttpStatus.OK).build();
  }


}
```

ItemSetControllerTest:

```java

  @Test
  @Sql(scripts = "/controller/test-itemset.sql", executionPhase = ExecutionPhase.BEFORE_TEST_METHOD)
  @Sql(scripts = "/controller/cleanup.sql", executionPhase = ExecutionPhase.AFTER_TEST_METHOD)
  public void testItemSetCreatedWithErrorNamespaceId() {
    String appId = "someAppId";
    AppDTO app =
        restTemplate.getForObject("http://localhost:" + port + "/apps/" + appId, AppDTO.class);

    ClusterDTO cluster = restTemplate.getForObject(
        "http://localhost:" + port + "/apps/" + app.getAppId() + "/clusters/default",
        ClusterDTO.class);

    NamespaceDTO namespace =
        restTemplate.getForObject("http://localhost:" + port + "/apps/" + app.getAppId()
            + "/clusters/" + cluster.getName() + "/namespaces/application", NamespaceDTO.class);

    Assert.assertEquals("someAppId", app.getAppId());
    Assert.assertEquals("default", cluster.getName());
    Assert.assertEquals("application", namespace.getNamespaceName());

    ItemChangeSets itemSet = new ItemChangeSets();
    itemSet.setDataChangeLastModifiedBy("created");
    RestTemplate createdTemplate = (new TestRestTemplate()).getRestTemplate();
    createdTemplate.setMessageConverters(restTemplate.getMessageConverters());

    int createdSize = 3;
    for (int i = 0; i < createdSize; i++) {
      ItemDTO item = new ItemDTO();
      item.setNamespaceId(namespace.getId() + i);
      item.setKey("key_" + i);
      item.setValue("created_value_" + i);
      itemSet.addCreateItem(item);
    }

    ResponseEntity<Map> response =
        createdTemplate.postForEntity(
            "http://localhost:" + port + "/apps/" + app.getAppId() + "/clusters/"
                + cluster.getName() + "/namespaces/" + namespace.getNamespaceName() + "/itemset",
            itemSet, Map.class);
    Assert.assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
    Map body = response.getBody();
    Assert.assertEquals(body.get("exception"), BadRequestException.class.getName());
  }
```

**Comment by huayaoyue6** [comment]
加了测试用例。

**Comment by huayaoyue6** [comment]
补充了测试用例

**Comment by nobodyiam** [comment]
@huayaoyue6 Thanks for the tip, I implemented in a different way but should also work.

**Comment by huayaoyue6** [comment]
👍

**Review by lepdou — COMMENTED** [review]
LGTM

**Review by lepdou — APPROVED** [review]

**Pull request merged**
