### PR TITLE
add self define config

### LINKED ISSUE #4259: feat: add self define meta server
**Is your feature request related to a problem? Please describe.**
In some environment，we put the config service and the admin service under the gateway, But for the portal we want to access the config service and admin service with gateway not the host which admin service and config service in, Such as different k8s environment. 
image

 So we want flexible config the admin service and the config service, and remove the stateful of config service(eureka).

### PR DESCRIPTION
**Pull request by gy09535**
## Which issue(s) this PR fixes:
Fixes #4259 

## Brief changelog

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by gy09535** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gy09535** [comment]
recheck

**Comment by nobodyiam** [comment]
It looks like self define discovery is very similar to [KubernetesDiscoveryService](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/KubernetesDiscoveryService.java), could we just reuse that instead?

**Comment by gy09535** [comment]
> 
Functionally speaking, it is similar, but semantically it is different, k8s definition is through k8s service discovery to replace eureka, but in some non-k8s environments or complex deployment scenarios, we do not need to use k8s services as service discovery, then we need more flexible semantics to define this operation, if we use k8s service discovery, will not cause semantic mixing, conceptually unclear.

**Comment by gy09535** [comment]
> It looks like self define discovery is very similar to [KubernetesDiscoveryService](https://github.com/apolloconfig/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/KubernetesDiscoveryService.java), could we just reuse that instead?

Functionally speaking, it is similar, but semantically it is different, k8s definition is through k8s service discovery to replace eureka, but in some non-k8s environments or complex deployment scenarios, we do not need to use k8s services as service discovery, then we need more flexible semantics to define this operation, if we use k8s service discovery, can cause semantic mixing, conceptually unclear.

**Comment by nobodyiam** [comment]
Then I suppose we could do like this, in which `custom-defined` is the profile to be activated for those non-kubernetes environment, but we could share the same implementation.

```java
@Service
@Profile({"kubernetes", "custom-defined"})
public class KubernetesDiscoveryService implements DiscoveryService {
}
```

**Comment by gy09535** [comment]
> Then I suppose we could do like this, in which `custom-defined` is the profile to be activated for those non-kubernetes environment, but we could share the same implementation.
> 
> ```java
> @Service
> @Profile({"kubernetes", "custom-defined-discovery"})
> public class KubernetesDiscoveryService implements DiscoveryService {
> }
> ```

good idea 👍

**Pull request closed without merging**
