### PR TITLE
1、fix transcation invalid

### PR DESCRIPTION
**Pull request by ksice**
## What's the purpose of this PR

Fix transaction invalid

sonar prompt bug is "assignNamespaceRoleToConsumer's" @Transactional requirement is incompatible with the one for this method.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [x] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by ksice** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nobodyiam** [comment]
Thanks for the pull request. However, I'd like to learn more about what this change solves. Since there is no checked exception thrown for method `assignNamespaceRoleToConsumer`, I think adding `rollbackFor` or not is the same?

**Comment by ksice** [comment]
> Thanks for the pull request. However, I'd like to learn more about what this change solves. Since there is no checked exception thrown for method `assignNamespaceRoleToConsumer`, I think adding `rollbackFor` or not is the same?

rollbackfor can not be added but the @transcation annotation should be added, otherwise the transaction of the "assignNamespace" method will be invalidated

**Comment by nobodyiam** [comment]
Yes, but I think the `@Transactional` annotation is already added to `public List<ConsumerRole> assignNamespaceRoleToConsumer(String token, String appId, String namespaceName, String env)`?

**Comment by ksice** [comment]
> Yes, but I think the `@Transactional` annotation is already added to `public List<ConsumerRole> assignNamespaceRoleToConsumer(String token, String appId, String namespaceName, String env)`?

yes,But what I mean is that this method assignNamespaceRoleToConsumer(String token, String appId, String namespaceName) needs to add @Transactional, @Transactional has several failure scenarios, one of which is
The @Transactional annotation does not take effect in similar method calls, so when assignNamespaceRoleToConsumer(String token, String appId, String namespaceName) is called, it will cause assignNamespaceRoleToConsumer(String token, String appId, String namespaceName, String env)
@Transactional fails, I find it not roll back when I locally called assignNamespaceRoleToConsumer(String token, String appId, String namespaceName) to throw an exception。
E.g
image

**Comment by nobodyiam** [comment]
OK, then I think it's reasonable to add `@Transactional` to `assignNamespaceRoleToConsumer(String token, String appId, String namespaceName)`.

**Comment by ksice** [comment]
> OK, then I think it's reasonable to add `@Transactional` to `assignNamespaceRoleToConsumer(String token, String appId, String namespaceName)`.

ok, I modified the commit

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
