### PR TITLE
fix gray publish refresh item status(#4039)

### LINKED ISSUE #4039: 删除多个灰度配置，页面展示错误
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

删除多个灰度配置项并灰度发布，页面会存留一个刚删除的配置项

**复现**

通过如下步骤可以复现：

1. 新建多个灰度配置项并灰度发布
image

2. 删除灰度配置项
image

3. 灰度发布
image

**期望**

灰度发布点击后，界面不应该仍存在一个待发布的删除项；
这是个当前页面数据刷新的问题，重新载入下当前集群，待发布的删除项就会消失
apollo demo 站点 即可复现

**截图**
重新载入
image

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

### PR DESCRIPTION
**Pull request by CalebZYC**
## What's the purpose of this PR

XXXXX

## Which issue(s) this PR fixes:
Fixes #4039 

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Review by nobodyiam — DISMISSED** [review]
Thanks!

**Comment by nobodyiam** [comment]
@CalebZYC this is a bugfix for UI, I believe it's better to update the CHANGES.md

**Comment by CalebZYC** [comment]
> @CalebZYC这是 UI 的错误修复，我相信更新 CHANGES.md 会更好

已更新

**Comment by CalebZYC** [comment]
> @CalebZYC this is a bugfix for UI, I believe it's better to update the CHANGES.md

已更新

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
