### PR TITLE
fixFeature non properties diff

### PR DESCRIPTION
**Pull request by SunnyBoy-WYH**
## What's the purpose of this PR

fix some bug for https://github.com/apolloconfig/apollo/pull/4533

## Which issue(s) this PR fixes:
Fixes # https://github.com/apolloconfig/apollo/issues/4315

## Brief changelog
1. fix : textDiff cannot use problem
2. support : determined as not allEqual when some cluster key lacked
3. do not show [commentDiff] checkbox when non-prop tableDiff
4. prop file support textDiff , sort keys then can align text

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by SunnyBoy-WYH** [comment]
d5ac0801b566a84073d1008d2262e53

**Comment by SunnyBoy-WYH** [comment]
prop file textDiff

d5ac0801b566a84073d1008d2262e53

dc3db3c812c745f623293ab36075649

**Comment by SunnyBoy-WYH** [comment]
non-prop tableDiff dont show commentDIff checkBox

**Comment by SunnyBoy-WYH** [comment]
tableDiff support show not equal when some cluster lack key, for example,<mirror> lack, and <name>、<id> value not equal

**Review by lepdou — APPROVED** [review]
LGTM

**Pull request merged**
