### PR TITLE
fix：Optimize the default log path configuration

### PR DESCRIPTION
**Pull request by youngzil**
## What's the purpose of this PR

1. Optimize the default log path configuration

## Which issue(s) this PR fixes:
Fixes #

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/apolloconfig/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/apolloconfig/apollo/blob/master/CHANGES.md).

## Summary by CodeRabbit

- **New Features**
	- Enhanced logging configuration for improved flexibility in log management.

- **Documentation**
	- Updated Apollo development guides for clearer local setup instructions, including database requirements and running configurations.
	- Corrected default log output path and clarified service health verification steps.

### CODE REVIEW

**Comment by nobodyiam** [comment]
Is it only for local development? As there are logics to create the log folders in the startup.sh

https://github.com/apolloconfig/apollo/blob/4bdf66a62ad0ec30d06083b658935bfe7a245760/apollo-portal/src/main/scripts/startup.sh#L23-L26

**Comment by youngzil** [comment]
> Is it only for local development? As there are logics to create the log folders in the startup.sh
> 
> https://github.com/apolloconfig/apollo/blob/4bdf66a62ad0ec30d06083b658935bfe7a245760/apollo-portal/src/main/scripts/startup.sh#L23-L26

Yes, it is currently a problem in local development

**Comment by nobodyiam** [comment]
It doesn't work for me. The `apollo-assembly.log` was created in the current folder, likely because the `/opt` directory requires root access for creation. Additionally, I don't think this's an essential feature so I would prefer leaving it as is.
However, it's nice to change the assembly log file to `/opt/logs/apollo-assembly.log`.

**Comment by youngzil** [comment]
> It doesn't work for me. The `apollo-assembly.log` was created in the current folder, likely because the `/opt` directory requires root access for creation. Additionally, I don't think this's an essential feature so I would prefer leaving it as is. However, it's nice to change the assembly log file to `/opt/logs/apollo-assembly.log`.

Hi, you are right. I did a test and changed the path to a non-existent path under $HOME and found that it can start normally.
So I'm going to revert this change

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
